name: Dependabot-Slack
on:
  push:
    branches:
      - "*"
jobs:
  dependabot_slack:
    runs-on: ubuntu-latest
    name: Sends a message to Slack when a push, a pull request or an issue is made
      stepst
    steps:
      - name: Send message to Slack API
        uses: archive/github-actions-slackev2.8.0
        id: notify
        with:
          sLack-bot-user-oauth-access-token: $(l secrets.DEPENDABOT_SLACK_SECRET}Y
          slack-channel: <CHANNEL-NANE-HERE>
          slack-text: New Dependabot PR $lf github. event.pulL_request.html_url
